name: App Testing
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test Application with NUnit
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild .\el-proyecte-grande.sln

      - name: Install NUnit.ConsoleRunner
        run: nuget install NUnit.ConsoleRunner -Version 3.16.3 -DirectDownload -OutputDirectory .

      - name: Run Unit Tests
        run: ./NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe .\el-proyecte-grande-backend-test\bin\Debug\net6.0\el-proyecte-grande-backend-test.dll
